config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'shop' => 'pages#shop', as: 'shop'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post< ApplicationRecord
  #mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 4}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #comfirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  #http_basic_authenticate_with name: "admin", password: "ruby", 
    #except: [:index, :show]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страница про проект!'
    @text = 'Текст!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 
  #http_basic_authenticate_with name: "admin", password: "ruby", except: [:index, :show]
  def index 
    @post = Post.all
  end
  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end
  private def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(name){
    success: "alert-success",
    error: "alert-danger",
    danger: "alert-danger", 
    alert: "alert-warning",
    notice: "alert-info"
  }[name.to_sym] || name
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <div class ="container main">
        <div class= "row">
          <div class ="col-md-12">
            <%flash.each do |name, message| %>
              <div class="alert <%= bootstrap_class_for(name) %>"
                <button class="close" data-dismis="alert">&times;</button>
                <%= message%>
              </div>
              <% end %>
          </div>
      </div>
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Website</h5>
      <nav class="d-inline-flex mt-5 mt-md-0 ms-md-auto">
        <span class="me-4 py-text-dark"><%= link_to "Главная страница", home_path %></span>
        <span class="me-4 py-text-dark"><%= link_to "Про проект", about_path %></span>
        <span class="me-4 py-text-dark"><%= link_to "Магазин", shop_path %></span>
      </nav>
      <span class ="py-2 text-dark" ><%= link_to "Добавление статьи", new_post_path %></span>
      <ul class = "navbar-nav mr-auto">
       <% if user_signed_in? %>
         <li class="nav-item">
           <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
       </li>
         <%else %>
       <li class="nav-item">
         <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
       </li>
       <li class="nav-item">
        <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
       </li>
           <% end %>
     </ul>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
      
</html>

app/views/pages/about.html.erb
<h4><%=@heading%></h4>
<p>Проект "Вебсайт на Ruby" содержит шапку сайта. На ней ей следующие ссылки: "Главная страница", "Про проект", "Магазин", "Добавление страницы", "Вход" и "Регистрация".</p>

<p>При нажатии "Главная страница" происходит переход на главную страницу сайта, где представлены все статьи с заголовком и содержанием. Также есть кнопка "Читать далее", где зарегестрировавшиеся могут изменить/удалить статью и оставить комментарии (к сожалению, зарегестрировавшиеся могут редактировать/удалять как и свои, так и чужие посты). Кнопки изменить/удалить не появляются, если человек не вошёл под своим логином. </p>
<p>При нажатии "Про проект" происходит переход на страницу, где представлена информация о моём проекте.</p>

<p>При нажатии кнопки "Магазин" происходит переход на страницу, где представлен ассортимент магазина (к сожалению, более тщательно функционал не реализовал).</p>

<p>При нажатии кнопки "Регистрация" происходит переход на страницу с регистрацией. После регистрации ты можешь пользоваться функционалом сайта.</p>

<p>Если ты зарегестрировался, то при нажатии кнопки "Войти" и указании логина и пароля ты сможешь пользоваться функционалом сайта.</p>

app/views/pages/shop.html.erb
<h1>Инфа про мой магазин</h1>

app/views/posts/edit.html.erb
<h2>Редактирование поста </h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%= msg %> </div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end%>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post|%>
  <div class="alert alert-light">
   <h3><%=post.title %></h3>
   <h3><%=post.body %></h3>
   <%= link_to "Читать далее", post_path(post), :class =>'btn btn-outline-primary'%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста </h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%= msg %> </div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
 <!--<div class="form-group">
    <%= f.file_field :image %>
  </div>-->
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end%>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
<p><%=@post.body%></p>
<hr>
<% if user_signed_in? %>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= button_to "Удалить пост :(", post_path(@post), method: :delete, :class => 'btn btn-danger' %>
  <% end %>
<hr>
  <h2>Все комментарии</h2>
<% @post.comments.each do |comment|%>
  <div class="alert alert-light">
   <p><strong><%= comment.username %></strong>: <%=comment.body%></p>
  </div>
<% end %>
<hr>
<h2>Добавление комментария</h2>
<%= form_for([@post,@post.comments.build]) do |f|%>

  <p>
    Пользователь<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст комментария<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Добавить комментарий",{:class => 'btn btn-warning'}) %>
  </p>
<% end%>